Include copy of v1.18 source archive and note unstable hashes

diff --git a/build b/build
--- a/build
+++ b/build
@@ -21,8 +21,10 @@ getsha1()
 FS118='http://fossil-scm.org/index.html/tarball/fossil-v1.18.tar.gz?uuid=df9da91ba8'
 FS118_O='fossil-v1.18.tar.gz'
 FS118_D='fossil-v1.18'
-FS118_MD5=8f4eca8f7c0fc4a3d7566c54462fb725
-FS118_SHA1=449414cb6e6cff15ce670b32cddc34bb8857d160
+FS118_OMD5=8f4eca8f7c0fc4a3d7566c54462fb725
+FS118_OSHA1=449414cb6e6cff15ce670b32cddc34bb8857d160
+FS118_NMD5=e6fa34c8803f1a1ce22b8a89224495bf
+FS118_NSHA1=a5c8ce53c8d4c5d0188b095e97fee8e8bded0777
 
 GEX='http://repo.or.cz/r/git-export-filter.git'
 GEX_D='git-export-filter.git'
@@ -34,24 +36,33 @@ for util in curl openssl sed tar patch make git; do
   fi
 done
 
-if ! [ -r "$FS118_O" ]; then
-  echo "Downloading $FS118 to $FS118_O" >&2
-  eval "curl $CURLOPT0 -o '$FS118_O' '$FS118'"
-fi
-checkmd5="$(getmd5 "$FS118_O")"
-checksha1="$(getsha1 "$FS118_O")"
-bad=
-if [ "$FS118_MD5" != "$checkmd5" ]; then
-  bad=1
-  echo "Wrong md5 checksum $checkmd5 (expected $FS118_MD5) for $FS118_O" >&2
-fi
-if [ "$FS118_SHA1" != "$checksha1" ]; then
-  bad=1
-  echo "Wrong sha1 checksum $checksha1 (expected $FS118_SHA1) for $FS118_O" >&2
-fi
-if [ -n "$bad" ]; then
-  echo "Checksum verifcation failed for $FS118_O" >&2
-  exit 1
+check_hashes() {
+  checkmd5="$(getmd5 "$1")"
+  checksha1="$(getsha1 "$1")"
+  bad=
+  if [ "$FS118_OMD5" != "$checkmd5" ] && [ "$FS118_NMD5" != "$checkmd5" ]; then
+    bad=1
+    echo "Wrong md5 checksum $checkmd5 (expected $FS118_OMD5 or $FS118_NMD5) for $1" >&2
+  fi
+  if [ "$FS118_OSHA1" != "$checksha1" ] && [ "$FS118_NSHA1" != "$checksha1" ]; then
+    bad=1
+    echo "Wrong sha1 checksum $checksha1 (expected $FS118_OSHA1 or $FS118_NSHA1) for $1" >&2
+  fi
+  if [ -n "$bad" ]; then
+    echo "Checksum verifcation failed for $1" >&2
+    return 1
+  fi
+  return 0
+}
+
+if [ -r "archives/$FS118_O" ] && check_hashes "archives/$FS118_O"; then
+    FS118_O="archives/$FS118_O"
+else
+  if ! [ -r "$FS118_O" ]; then
+    echo "Downloading $FS118 to $FS118_O" >&2
+    eval "curl $CURLOPT0 -o '$FS118_O' '$FS118'"
+  fi
+  check_hashes "$FS118_O" || exit 1
 fi
 
 if ! [ -r "$FS118_D/Makefile" ]; then
